---
title: "Homework 6"
author: Yuqi Wang
output: github_document
---

```{r}
library(tidyverse)
library(modelr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Problem 1
```{r}
homicide_df = read_csv(file = "./data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    victim_age = as.numeric(victim_age),
    resolved = case_when(
      disposition  == "Closed without arrest" ~ "0",
      disposition  == "Open/No arrest" ~ "0",
      disposition  == "Closed by arrest" ~ "1",
    )
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa_AL") %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex)
```

start with one city:
```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "Baltimore_MD") %>% 
  mutate(resolved = as.numeric(resolved))

glm(resolved ~ victim_age + victim_sex,
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96*std.error),
    CI_upper = exp(estimate + 1.96*std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```

Try this accross cities:
```{r}
model_results = homicide_df %>%
  mutate(resolved = as.numeric(resolved)) %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = map(.x = data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())), 
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96*std.error),
    CI_upper = exp(estimate + 1.96*std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI"))
```

Make a plot

```{r}
model_results %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper))
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


## Problem 2

Find some residuals:
```{r}
baby_df = read_csv()
```

fit a model:
```{r}
model_fit = lm(bwt ~ gaweeks, data = baby_df)
```

```{r}
baby_df %>% 
  modelr::add_residuals(model_fit) %>% 
  ggplot(aes(x = resid))+
  geom_density()
```

conclusion: the residuals are not heavily skewed and normal

```{r}
baby_df %>% 
  modelr::add_residuals(model_fit) %>% 
  ggplot(aes(x = gaweeks, y = resid))+
  geom_point()
```

conclusion: whether there are outlier values or trends that shows this is not linear relationship


